### ISSUE TITLE
Add Error throwing for !torture

### ISSUE THREAD

**Issue by CaptainZwT** [NobleWolf42/Stormageddon-Bot#17]
if !torture kicks a admin, it throws a lack of permissions in console error, that should be edited to look better and most of all not cause the host to be alarmed, as the discord bot isn't facing issues, it simply cannot kick admins, clearly.

Refer to [documentation](https://discordjs.guide/popular-topics/collectors.html#await-messages) on discord bots.

**Comment by NobleWolf42** [comment]
updated the error handeling to be less obtrusive
