### ISSUE TITLE
Destiny 2: Add better system for joining fireteams

### ISSUE THREAD

**Issue by JLoganMilliron** [NobleWolf42/Stormageddon-Bot#18]
Until we add a database to keep track of information,

for now, add a !d2 host command allowing a user to host a fireteam.
At that point !d2 join command allows users to join that fireteam.

When the fireteam is first hosted, a user joins or when !d2 fireteams is called,
a tabled display showing users in the fireteam displayed.

Refer to [Destiny API documentation](https://github.com/Bungie-net/api).
Refer to [documentation](https://discordjs.guide/popular-topics/collectors.html#await-messages) on discord bots.

**Comment by CaptainZwT** [comment]
According to further reading of the documentation.

The Destiny 2 API does not support joining or creating fireteams through the API.
