### ISSUE TITLE
Destiny 2: Add role based on clan membership

### ISSUE THREAD

**Issue by JLoganMilliron** [NobleWolf42/Stormageddon-Bot#19]
Specifically aimed at the majority of the current server's clan,

If the user is in said clan (The Taken Clan Name) add them to specified role for clan members.

Refer to [Destiny API documentation](https://github.com/Bungie-net/api).
Refer to [documentation](https://discordjs.guide/popular-topics/collectors.html#await-messages) on discord bots.

**Comment by CaptainZwT** [comment]
Not particularly invested in this, as @NobleWolf42 mentioned it. It doesn't seem to be all that great of an idea on further evaluation.

**Comment by NobleWolf42** [comment]
This has since been deemed outside the scope of the bot, possible feature we add in the future, but not now.
