### ISSUE TITLE
!modhelp (message)

### ISSUE THREAD

**Issue by CaptainZwT** [NobleWolf42/Stormageddon-Bot#27]
A command that any user (except some role for small children) that would allow them to write a message in WHISPER to Stormaggedon, that would result in Stormaggedon writing everyone who has X role.

**Comment by NobleWolf42** [comment]
The only issues I forsee with this is that the bot will be on multipul servers, thus we would need to code out a check to see what server they are from and if multipul, determine the one they are trying to pm.

**Comment by CaptainZwT** [comment]
@NobleWolf42 So let's additionally set up a specific .json that can be written to using a command and a @ that puts them in the list of moderators who recieve these whispers. That would resolve the issue, without the need of adding to any looop style processing, and put most of the work on server admins.

**Comment by NobleWolf42** [comment]
is this a way to whisper to the moderators of a server, or the bot?

**Comment by CaptainZwT** [comment]
@NobleWolf42 the bot passes on the message, making it one easy way to do it. In otherwords one could call the command and the bot would whisper a certain role with said message.

**Comment by NobleWolf42** [comment]
so we are ditching them whispering storm bot?

**Comment by CaptainZwT** [comment]
it's both, in a ideal world.

That keeps it strictly private.

**Comment by NobleWolf42** [comment]
ok, so do we want to structure the command !modmail <SERVER_NAME> <MESSAGE>

**Comment by NobleWolf42** [comment]
This was completed and implemented
